version: '3.8'
services:
  nexus:
    image: ghcr.io/andreitere/tikshared:${VERSION:-latest}
    container_name: tikshared
    volumes:
      - "tdownloads:/downloads"
    ports:
      - "3333:3000"
    networks:
      - public_bridge
    deploy:
      resources:
        limits:
          memory: "1g"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tikshared.rule=Host(`tikshared.cloudcrafts.club`)"
      - "traefik.http.services.tikshared.loadbalancer.server.port=3333"
      - "traefik.http.routers.tikshared.middlewares=traefik-https-redirect"
      - "traefik.http.routers.tikshared.tls=true"
      - "traefik.http.routers.tikshared.tls.certresolver=cloudflare"
      - "com.centurylinklabs.watchtower.enable=false"
volumes:
  tdownloads:
    external: true

networks:
  public_bridge:
    name: public_bridge
    external: true