version: '3.8'
services:
  nexus:
    image: ghcr.io/andreitere/tikshared:${VERSION:-latest}
    container_name: tikshared
    volumes:
      - "tdownloads:/downloads"
    environment:
    deploy:
      resources:
        limits:
          memory: "1g"
volumes:
  tdownloads:
    external: true
