version: '3.8'
services:
  tikshared:
    image: ghcr.io/andreitere/tikshared:${VERSION:-latest}
    container_name: tikshared
    volumes:
      - "tdownloads:/app/downloads"
    ports:
      - "3333:3000"
    environment:
      - API_KEY=${API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - public_bridge
    deploy:
      resources:
        limits:
          memory: "1g"
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  tdownloads:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/external/tshared


networks:
  public_bridge:
    name: public_bridge
    external: true